//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_CV.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int id_Aspirante { get; set; }
        public string Nombre_completo { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Email { get; set; }
        public string Departamento { get; set; }
        public string Objetivo { get; set; }
        public string Foto { get; set; }
        public string Ins_bachillerato { get; set; }
        public Nullable<System.DateTime> Fecha_inicio1 { get; set; }
        public Nullable<System.DateTime> Fecha_finalizacion1 { get; set; }
        public string Titulo_bto { get; set; }
        public string Departamento_bto { get; set; }
        public string Ins_universidad { get; set; }
        public Nullable<System.DateTime> Fecha_inicio2 { get; set; }
        public Nullable<System.DateTime> Fecha_finalizacion2 { get; set; }
        public string Titulo_uni { get; set; }
        public string Departamento_uni { get; set; }
        public string Habilidades { get; set; }
        public string Competencias { get; set; }
        public string Dominio { get; set; }
        public string Ref_nombre1 { get; set; }
        public Nullable<int> Ref_telefono1 { get; set; }
        public string Ref_tipo1 { get; set; }
        public string Ref_nombre2 { get; set; }
        public Nullable<int> Ref_telefono2 { get; set; }
        public string Ref_tipo2 { get; set; }
        public string Estado { get; set; }
        public string exp_laboral { get; set; }
        public string cargo { get; set; }
        public Nullable<System.DateTime> inicio_cargo { get; set; }
        public Nullable<System.DateTime> fin_cargo { get; set; }
        public string departamento_trabajo { get; set; }
        public byte[] fotografia { get; set; }
    }
}
